package de.chucknorris.client.chucknorristrayicon.settings;

/**
 *
 * @author Alexander Friedrichs
 */
public final class Constants {
    
    public static final String CONFIGSCREEN = "menu.settings";
    public static final String RESOURCEBUNDLE = "de.chucknorris.client.locale.ChuckNorris";
    public static final String NEWCITATION = "menu.createCitation";
    public static final String CITATION = "Citation";
    public static final String QUIT = "menu.exit";
    public static final String PAUSE = "menu.pause";
    public static final String TITLE = "trayicon.title";
    public static final String TIMERACTIONCOMMAND = "TimerAction";  
    public static final String DELAY = "delay";
    public static final String DELAY_TEXT = "screen.settings.delay.text";
    public static final String DEFAULT_DELAY = "600000";
    public static final String SETTINGS_FOLDER = ".cn";
    public static final String SETTINGS_FILE = "chucknorris.prop"; 
    public static final String SETTINGS_COMMENT = "AutoGenerated settings file from the chuck norris trayicon";
    public static final String SETTINGS_PROXY_HOST = "http.proxyHost";
    public static final String SETTINGS_PROXY_PORT = "http.proxyPort";
    public static final String SETTINGS_PROXY_USER = "http.proxyUser";
    public static final String SETTINGS_PROXY_PASS = "http.proxyPassword";

    private Constants() {}    
    
}
